-- Seed data generated from the prototype's builtin catalogue.
-- Regenerate with: node gen-seed.mjs (see scratchpad script used to produce this file).

insert into public.stores (name, slug, display_order) values
  ('Tesco', 'tesco', 0),
  ('Aldi', 'aldi', 1),
  ('Asda', 'asda', 2),
  ('Sainsbury''s', 'sainsbury-s', 3),
  ('Morrisons', 'morrisons', 4)
;
-- Lidl is deliberately not listed: no online source publishes real per-item Lidl prices
-- (comparethetrolley.co.uk excludes it, trolley.co.uk has no Lidl store data, and lidl.co.uk
-- has no searchable product catalogue), so there's no honest way to populate it.

insert into public.ingredients (key, name, pack_label) values
  ('chickenThigh', 'Chicken thigh fillets', '1kg'),
  ('chickenBreast', 'Chicken breast fillets', '1kg'),
  ('turkeyMince', '2% fat turkey mince', '500g'),
  ('mince', '5% fat beef mince', '500g'),
  ('fish', 'Frozen white fish fillets', '520g'),
  ('tuna', 'Tuna chunks in brine', '4 × 145g'),
  ('sardines', 'Sardines in tomato sauce', '120g tin'),
  ('eggs', 'Eggs', '12 pack'),
  ('tofu', 'Firm tofu', '396g'),
  ('greekYog', 'Fat-free Greek yoghurt', '1kg'),
  ('cottage', 'Cottage cheese', '300g'),
  ('milk', 'Semi-skimmed milk', '2 pints'),
  ('lentils', 'Red split lentils', '1kg'),
  ('chickpeas', 'Chickpeas', '400g tin'),
  ('kidneyBeans', 'Kidney beans', '400g tin'),
  ('pb', 'Peanut butter', '340g'),
  ('oats', 'Porridge oats', '1kg'),
  ('rice', 'Long grain rice', '1kg'),
  ('pasta', 'Wholewheat pasta', '500g'),
  ('noodles', 'Egg noodles', '250g'),
  ('wraps', 'Tortilla wraps', '8 pack'),
  ('bread', 'Wholemeal bread', '800g loaf'),
  ('potatoes', 'White potatoes', '2.5kg'),
  ('frozenVeg', 'Frozen mixed vegetables', '1kg'),
  ('toms', 'Chopped tomatoes', '400g tin'),
  ('onions', 'Onions', '1kg'),
  ('banana', 'Bananas', '1kg'),
  ('pantry', 'Oil, spices & sauces', 'store cupboard')
;

-- Prices are real, sourced from comparethetrolley.co.uk and trolley.co.uk (checked 19 Jul
-- 2026), scaled to each ingredient's pack_label. A few cells use the closest real product
-- available at that store where no exact match exists — see
-- supabase/migrations/20260719210000_real_ingredient_prices.sql for the full list of
-- substitutions and their rationale.
insert into public.ingredient_prices (ingredient_id, store_id, price)
select i.id, s.id, v.price
from (values
  ('chickenThigh', 'tesco', 7.25),
  ('chickenThigh', 'aldi', 8.13),
  ('chickenThigh', 'asda', 6.84),
  ('chickenThigh', 'sainsbury-s', 6.95),
  ('chickenThigh', 'morrisons', 7.25),
  ('chickenBreast', 'tesco', 7.69),
  ('chickenBreast', 'aldi', 6.69),
  ('chickenBreast', 'asda', 6.94),
  ('chickenBreast', 'sainsbury-s', 6.69),
  ('chickenBreast', 'morrisons', 6.99),
  ('turkeyMince', 'tesco', 4.90),
  ('turkeyMince', 'aldi', 3.99),
  ('turkeyMince', 'asda', 4.80),
  ('turkeyMince', 'sainsbury-s', 4.95),
  ('turkeyMince', 'morrisons', 4.00),
  ('mince', 'tesco', 5.19),
  ('mince', 'aldi', 5.19),
  ('mince', 'asda', 5.19),
  ('mince', 'sainsbury-s', 5.19),
  ('mince', 'morrisons', 5.40),
  ('fish', 'tesco', 10.83),
  ('fish', 'aldi', 5.76),
  ('fish', 'asda', 10.83),
  ('fish', 'sainsbury-s', 11.20),
  ('fish', 'morrisons', 9.75),
  ('tuna', 'tesco', 2.60),
  ('tuna', 'aldi', 2.49),
  ('tuna', 'asda', 2.60),
  ('tuna', 'sainsbury-s', 2.60),
  ('tuna', 'morrisons', 5.34),
  ('sardines', 'tesco', 0.49),
  ('sardines', 'aldi', 0.49),
  ('sardines', 'asda', 0.60),
  ('sardines', 'sainsbury-s', 0.60),
  ('sardines', 'morrisons', 0.60),
  ('eggs', 'tesco', 2.85),
  ('eggs', 'aldi', 2.49),
  ('eggs', 'asda', 2.85),
  ('eggs', 'sainsbury-s', 2.95),
  ('eggs', 'morrisons', 2.85),
  ('tofu', 'tesco', 1.90),
  ('tofu', 'aldi', 1.88),
  ('tofu', 'asda', 2.12),
  ('tofu', 'sainsbury-s', 1.90),
  ('tofu', 'morrisons', 2.38),
  ('greekYog', 'tesco', 1.95),
  ('greekYog', 'aldi', 1.90),
  ('greekYog', 'asda', 1.86),
  ('greekYog', 'sainsbury-s', 1.70),
  ('greekYog', 'morrisons', 1.95),
  ('cottage', 'tesco', 1.65),
  ('cottage', 'aldi', 1.39),
  ('cottage', 'asda', 1.58),
  ('cottage', 'sainsbury-s', 1.60),
  ('cottage', 'morrisons', 2.06),
  ('milk', 'tesco', 1.21),
  ('milk', 'aldi', 1.20),
  ('milk', 'asda', 1.21),
  ('milk', 'sainsbury-s', 1.21),
  ('milk', 'morrisons', 1.21),
  ('lentils', 'tesco', 2.60),
  ('lentils', 'aldi', 1.13),
  ('lentils', 'asda', 3.94),
  ('lentils', 'sainsbury-s', 4.20),
  ('lentils', 'morrisons', 4.20),
  ('chickpeas', 'tesco', 0.45),
  ('chickpeas', 'aldi', 0.41),
  ('chickpeas', 'asda', 0.41),
  ('chickpeas', 'sainsbury-s', 0.41),
  ('chickpeas', 'morrisons', 0.37),
  ('kidneyBeans', 'tesco', 0.33),
  ('kidneyBeans', 'aldi', 0.39),
  ('kidneyBeans', 'asda', 0.39),
  ('kidneyBeans', 'sainsbury-s', 0.39),
  ('kidneyBeans', 'morrisons', 0.37),
  ('pb', 'tesco', 0.99),
  ('pb', 'aldi', 0.99),
  ('pb', 'asda', 1.80),
  ('pb', 'sainsbury-s', 1.25),
  ('pb', 'morrisons', 4.00),
  ('oats', 'tesco', 2.95),
  ('oats', 'aldi', 0.85),
  ('oats', 'asda', 4.50),
  ('oats', 'sainsbury-s', 0.85),
  ('oats', 'morrisons', 3.00),
  ('rice', 'tesco', 1.25),
  ('rice', 'aldi', 0.52),
  ('rice', 'asda', 2.76),
  ('rice', 'sainsbury-s', 1.25),
  ('rice', 'morrisons', 4.00),
  ('pasta', 'tesco', 0.75),
  ('pasta', 'aldi', 0.75),
  ('pasta', 'asda', 1.20),
  ('pasta', 'sainsbury-s', 0.69),
  ('pasta', 'morrisons', 0.69),
  ('noodles', 'tesco', 0.95),
  ('noodles', 'aldi', 1.08),
  ('noodles', 'asda', 1.15),
  ('noodles', 'sainsbury-s', 0.95),
  ('noodles', 'morrisons', 1.08),
  ('wraps', 'tesco', 0.99),
  ('wraps', 'aldi', 0.99),
  ('wraps', 'asda', 1.32),
  ('wraps', 'sainsbury-s', 0.99),
  ('wraps', 'morrisons', 1.40),
  ('bread', 'tesco', 0.75),
  ('bread', 'aldi', 0.55),
  ('bread', 'asda', 0.75),
  ('bread', 'sainsbury-s', 0.75),
  ('bread', 'morrisons', 0.74),
  ('potatoes', 'tesco', 1.65),
  ('potatoes', 'aldi', 1.65),
  ('potatoes', 'asda', 1.65),
  ('potatoes', 'sainsbury-s', 1.65),
  ('potatoes', 'morrisons', 3.90),
  ('frozenVeg', 'tesco', 1.65),
  ('frozenVeg', 'aldi', 0.99),
  ('frozenVeg', 'asda', 1.15),
  ('frozenVeg', 'sainsbury-s', 1.65),
  ('frozenVeg', 'morrisons', 0.99),
  ('toms', 'tesco', 0.43),
  ('toms', 'aldi', 0.43),
  ('toms', 'asda', 0.46),
  ('toms', 'sainsbury-s', 0.35),
  ('toms', 'morrisons', 0.47),
  ('onions', 'tesco', 0.95),
  ('onions', 'aldi', 0.95),
  ('onions', 'asda', 0.95),
  ('onions', 'sainsbury-s', 0.95),
  ('onions', 'morrisons', 0.95),
  ('banana', 'tesco', 1.07),
  ('banana', 'aldi', 1.07),
  ('banana', 'asda', 1.07),
  ('banana', 'sainsbury-s', 0.95),
  ('banana', 'morrisons', 1.20),
  ('pantry', 'tesco', 2),
  ('pantry', 'aldi', 2),
  ('pantry', 'asda', 2),
  ('pantry', 'sainsbury-s', 2),
  ('pantry', 'morrisons', 2)
) as v(ingredient_key, store_slug, price)
join public.ingredients i on i.key = v.ingredient_key
join public.stores s on s.slug = v.store_slug
;

insert into public.snack_presets (name, kcal, protein_g, cost, sort_order) values
  ('Bowl of cereal & milk', 260, 9, 0.4, 0),
  ('Meal deal (sandwich, snack, drink)', 650, 24, 3.6, 1),
  ('Toast with butter (2 slices)', 240, 7, 0.2, 2),
  ('Protein bar', 210, 20, 1.5, 3),
  ('Protein shake (whey + water)', 120, 24, 0.7, 4),
  ('Banana', 95, 1, 0.15, 5),
  ('Apple', 80, 0, 0.3, 6),
  ('Yoghurt pot', 130, 12, 0.6, 7),
  ('Packet of crisps', 165, 2, 0.75, 8),
  ('Chocolate bar', 230, 3, 0.85, 9),
  ('Biscuits (2)', 150, 2, 0.15, 10),
  ('Sausage roll', 330, 10, 1.3, 11),
  ('Latte (medium)', 190, 10, 3.4, 12),
  ('Can of fizzy drink', 140, 0, 1, 13),
  ('Pint of lager', 200, 1, 5.2, 14),
  ('Takeaway (average portion)', 1000, 35, 9.5, 15)
;

insert into public.meals (slug, name, servings, protein_g, kcal, is_veggie, time_label, description, method, source) values
  ('traybake', 'Chicken thigh & veg traybake', 4, 38, 520, false, '50 min', 'Thighs roasted over rice and frozen veg. One tray, minimal washing up.', '["Heat the oven to 200°C fan. Season the thighs well with oil, salt, pepper and any spices you like.","Tip the rice into a deep roasting tray with 600ml boiling water and a pinch of salt. Scatter over the frozen veg and sliced onions.","Sit the thighs on top, cover tightly with foil and roast for 30 minutes.","Remove the foil and roast 15 more minutes until the chicken is browned and the rice has absorbed the water.","Rest 5 minutes, fluff the rice and serve. Portions freeze well."]'::jsonb, 'builtin'),
  ('lentilCurry', 'Lentil & chickpea curry', 4, 24, 460, true, '35 min', 'Storecupboard curry with rice. Freezes brilliantly, costs pennies.', '["Soften the chopped onions in oil for 5 minutes, then add 2 tbsp curry powder and cook 1 minute.","Add the lentils, tomatoes and 700ml water. Simmer 20 minutes, stirring now and then, until the lentils are soft.","Stir in the drained chickpeas and simmer 5 more minutes. Season to taste.","Meanwhile cook the rice in boiling salted water for 12 minutes and drain.","Serve the curry over rice. Freezes in portions for up to 3 months."]'::jsonb, 'builtin'),
  ('tunaBake', 'Tuna pasta bake', 3, 34, 490, false, '35 min', 'Three tins of tuna, tomato sauce, wholewheat pasta.', '["Cook the pasta 2 minutes short of the packet time and drain, keeping a mug of pasta water.","Fry the chopped onion in oil until soft, add the tomatoes and a splash of pasta water, and simmer 5 minutes.","Stir in the drained tuna and the pasta. Season with salt, pepper and dried herbs.","Tip into a baking dish and bake at 200°C fan for 12–15 minutes until bubbling at the edges."]'::jsonb, 'builtin'),
  ('yogBowl', 'Greek yoghurt power bowl', 1, 28, 420, true, '5 min', 'Yoghurt, oats, peanut butter and banana. 5-minute breakfast.', '["Spoon the yoghurt into a bowl and stir through the oats.","Slice the banana over the top.","Finish with a spoonful of peanut butter. Add a drizzle of honey if you have it."]'::jsonb, 'builtin'),
  ('friedRice', 'Egg & veg fried rice', 2, 22, 480, true, '15 min', 'Four eggs scrambled through rice and veg with soy sauce.', '["Cook the rice (or use leftover cold rice — even better).","Get a large frying pan or wok very hot with a little oil and stir-fry the frozen veg for 3 minutes.","Push the veg aside, crack in the eggs and scramble them in the pan.","Add the rice and 2 tbsp soy sauce, and stir-fry everything together for 3–4 minutes."]'::jsonb, 'builtin'),
  ('chilli', 'Lean beef chilli', 4, 30, 510, false, '45 min', '5% mince bulked with beans — more protein, lower cost per serving.', '["Brown the mince in a large pan over high heat, breaking it up. Add the chopped onions and cook 5 minutes.","Stir in 1 tbsp each of cumin, paprika and chilli powder and cook 1 minute.","Add the tomatoes and drained beans, and simmer gently for 25–30 minutes.","Cook the rice for the last 12 minutes.","Season the chilli and serve over rice. Even better the next day."]'::jsonb, 'builtin'),
  ('cottageToast', 'Cottage cheese & eggs on toast', 1, 32, 430, true, '10 min', 'Two slices, two eggs, half a tub of cottage cheese.', '["Toast the bread.","Soft-boil or fry the eggs — about 6 minutes for jammy boiled eggs.","Spread the cottage cheese thickly on the toast, top with the eggs and plenty of black pepper."]'::jsonb, 'builtin'),
  ('fishRice', 'Baked fish, rice & greens', 2, 30, 440, false, '25 min', 'Frozen white fish is one of the cheapest lean proteins going.', '["Heat the oven to 200°C fan. Put the fish (straight from frozen is fine) on a lined tray, rub with oil, salt and pepper.","Bake for 18–20 minutes until the fish flakes easily.","Meanwhile cook the rice, adding the frozen veg to the pan for the last 4 minutes.","Drain, plate up and serve the fish on top with a squeeze of lemon if you have one."]'::jsonb, 'builtin'),
  ('tofuStir', 'Crispy tofu stir-fry', 2, 22, 430, true, '25 min', 'Whole block of tofu, pan-fried until golden, over rice.', '["Press the tofu between kitchen paper for 10 minutes, then cut into cubes and toss in 1 tbsp cornflour.","Start the rice cooking.","Fry the tofu in a hot pan with oil for 8–10 minutes, turning until golden on all sides. Set aside.","Stir-fry the veg 3 minutes, return the tofu, add 2 tbsp soy sauce and toss. Serve over the rice."]'::jsonb, 'builtin'),
  ('onOats', 'Peanut butter overnight oats', 1, 20, 410, true, '5 min + 🌙', 'Made the night before with milk, yoghurt and peanut butter.', '["Stir the oats, milk, yoghurt and peanut butter together in a jar or tub.","Cover and refrigerate overnight (or at least 4 hours).","Loosen with a splash of milk in the morning. Keeps 2–3 days, so make a few at once."]'::jsonb, 'builtin'),
  ('turkeyRagu', 'Turkey mince ragu & pasta', 4, 32, 500, false, '35 min', '2% turkey mince is leaner and cheaper per gram of protein than beef.', '["Soften the chopped onions in oil, then add the turkey mince and brown it, breaking it up.","Add the tomatoes, a tin of water, dried herbs and seasoning. Simmer 20 minutes until thick.","Cook the pasta for the last 10 minutes and drain.","Toss the pasta through the ragu with a splash of pasta water."]'::jsonb, 'builtin'),
  ('sardinesToast', 'Sardines on toast', 1, 22, 380, false, '5 min', 'The classic budget protein hit — plus omega-3 and calcium.', '["Toast the bread.","Warm the sardines in their sauce for a minute in a small pan or the microwave.","Pile onto the toast, mash lightly with a fork and add plenty of black pepper."]'::jsonb, 'builtin'),
  ('jacketTuna', 'Jacket potato, tuna & cottage cheese', 2, 30, 450, false, '15 min', 'Microwave the spuds if you''re short on time. Huge and filling.', '["Prick the potatoes and microwave on high for 8–10 minutes until soft (or bake 1 hour at 200°C for crispy skins).","Mix the drained tuna with the cottage cheese, black pepper and a dash of vinegar or lemon.","Split the potatoes, fluff the insides and pile the tuna mix on top."]'::jsonb, 'builtin'),
  ('chickenCurry', 'Chicken & chickpea curry', 4, 35, 520, false, '40 min', 'Thighs stretched further with chickpeas. Better than a takeaway.', '["Brown the diced chicken thighs in oil over high heat, then remove.","Soften the chopped onions in the same pan, add 2 tbsp curry powder and cook 1 minute.","Return the chicken with the tomatoes, drained chickpeas and half a tin of water. Simmer 20 minutes.","Cook the rice for the last 12 minutes, then serve."]'::jsonb, 'builtin'),
  ('beanChilli', 'Three-bean chilli', 4, 20, 430, true, '35 min', 'Vegan, freezer-friendly and about as cheap as dinner gets.', '["Soften the chopped onions in oil, then add 1 tbsp each of cumin, paprika and chilli powder.","Add the tomatoes and all the drained beans, and simmer 20–25 minutes until rich and thick.","Cook the rice for the last 12 minutes.","Season generously and serve. Freezes brilliantly in portions."]'::jsonb, 'builtin'),
  ('pancakes', 'Banana protein pancakes', 2, 24, 440, true, '20 min', 'Oats, eggs and banana blitzed into a batter, topped with yoghurt.', '["Blitz the oats, eggs and bananas into a smooth batter (a blender or stick blender works).","Heat a non-stick pan with a little oil and fry small pancakes 2 minutes per side.","Stack and top with the Greek yoghurt and any fruit you have."]'::jsonb, 'builtin'),
  ('shakshuka', 'Chickpea shakshuka', 2, 24, 420, true, '25 min', 'Eggs baked in spiced tomatoes and chickpeas, bread for dipping.', '["Soften the chopped onion in oil, add 1 tsp each paprika and cumin, then the tomatoes and drained chickpeas.","Simmer 10 minutes until thickened, then make 4 wells in the sauce.","Crack an egg into each well, cover and cook 5–7 minutes until the whites are set.","Serve straight from the pan with toasted bread for dipping."]'::jsonb, 'builtin'),
  ('peanutNoodles', 'Peanut tofu noodles', 2, 24, 520, true, '20 min', 'Peanut butter, soy and a splash of pasta water make the sauce.', '["Cube and fry the tofu in a hot oiled pan until golden, about 8 minutes.","Cook the noodles, adding the frozen veg for the last 3 minutes. Keep a mug of the water.","Whisk the peanut butter with 2 tbsp soy sauce and enough noodle water to make a pourable sauce.","Toss everything together and finish with chilli flakes."]'::jsonb, 'builtin'),
  ('fajitaWraps', 'Chicken fajita wraps', 3, 35, 480, false, '20 min', 'Sliced breast, charred onions, warm wraps. Batch it for lunches.', '["Slice the chicken and onions. Toss the chicken in 1 tbsp fajita spice mix (paprika, cumin, chilli, garlic).","Get a pan very hot with oil and cook the chicken 5–6 minutes until charred and cooked through. Set aside.","Cook the onions in the same pan until softened and browned at the edges.","Warm the wraps, fill and roll. Cold ones make a great packed lunch."]'::jsonb, 'builtin')
;

insert into public.meal_ingredients (meal_id, ingredient_id, pack_fraction, human_quantity, sort_order)
select me.id, ing.id, v.pack_fraction, v.human_quantity, v.sort_order
from (values
  ('traybake', 'chickenThigh', 0.6, '600g', 0),
  ('traybake', 'rice', 0.3, '300g', 1),
  ('traybake', 'frozenVeg', 0.5, '500g', 2),
  ('traybake', 'onions', 0.2, '2 onions', 3),
  ('traybake', 'pantry', 0.08, 'oil & seasoning', 4),
  ('lentilCurry', 'lentils', 0.3, '300g', 0),
  ('lentilCurry', 'chickpeas', 2, '2 tins', 1),
  ('lentilCurry', 'toms', 1, '1 tin', 2),
  ('lentilCurry', 'onions', 0.25, '2 onions', 3),
  ('lentilCurry', 'rice', 0.3, '300g', 4),
  ('lentilCurry', 'pantry', 0.1, 'curry spices & oil', 5),
  ('tunaBake', 'tuna', 0.75, '3 tins', 0),
  ('tunaBake', 'pasta', 0.6, '300g', 1),
  ('tunaBake', 'toms', 1, '1 tin', 2),
  ('tunaBake', 'onions', 0.15, '1 onion', 3),
  ('tunaBake', 'pantry', 0.06, 'oil & herbs', 4),
  ('yogBowl', 'greekYog', 0.25, '250g', 0),
  ('yogBowl', 'oats', 0.06, '60g', 1),
  ('yogBowl', 'pb', 0.06, '20g', 2),
  ('yogBowl', 'banana', 0.15, '1 banana', 3),
  ('friedRice', 'eggs', 0.34, '4 eggs', 0),
  ('friedRice', 'rice', 0.25, '250g', 1),
  ('friedRice', 'frozenVeg', 0.4, '400g', 2),
  ('friedRice', 'pantry', 0.06, 'soy sauce & oil', 3),
  ('chilli', 'mince', 1, '500g', 0),
  ('chilli', 'kidneyBeans', 1.5, '1½ tins', 1),
  ('chilli', 'toms', 2, '2 tins', 2),
  ('chilli', 'onions', 0.25, '2 onions', 3),
  ('chilli', 'rice', 0.35, '350g', 4),
  ('chilli', 'pantry', 0.1, 'chilli spices', 5),
  ('cottageToast', 'cottage', 0.5, '150g', 0),
  ('cottageToast', 'bread', 0.15, '2 slices', 1),
  ('cottageToast', 'eggs', 0.17, '2 eggs', 2),
  ('fishRice', 'fish', 0.9, '2 large fillets', 0),
  ('fishRice', 'rice', 0.25, '250g', 1),
  ('fishRice', 'frozenVeg', 0.4, '400g', 2),
  ('fishRice', 'pantry', 0.06, 'oil, lemon & pepper', 3),
  ('tofuStir', 'tofu', 1, '1 block', 0),
  ('tofuStir', 'rice', 0.25, '250g', 1),
  ('tofuStir', 'frozenVeg', 0.5, '500g', 2),
  ('tofuStir', 'pantry', 0.08, 'soy, cornflour & oil', 3),
  ('onOats', 'oats', 0.08, '80g', 0),
  ('onOats', 'milk', 0.18, '200ml', 1),
  ('onOats', 'pb', 0.08, '25g', 2),
  ('onOats', 'greekYog', 0.1, '100g', 3),
  ('turkeyRagu', 'turkeyMince', 1, '500g', 0),
  ('turkeyRagu', 'pasta', 0.6, '300g', 1),
  ('turkeyRagu', 'toms', 2, '2 tins', 2),
  ('turkeyRagu', 'onions', 0.25, '2 onions', 3),
  ('turkeyRagu', 'pantry', 0.1, 'herbs, garlic & oil', 4),
  ('sardinesToast', 'sardines', 1, '1 tin', 0),
  ('sardinesToast', 'bread', 0.15, '2 slices', 1),
  ('sardinesToast', 'pantry', 0.02, 'black pepper', 2),
  ('jacketTuna', 'potatoes', 0.25, '2 large potatoes', 0),
  ('jacketTuna', 'tuna', 0.5, '2 tins', 1),
  ('jacketTuna', 'cottage', 0.5, '150g', 2),
  ('jacketTuna', 'pantry', 0.03, 'pepper & vinegar', 3),
  ('chickenCurry', 'chickenThigh', 0.5, '500g', 0),
  ('chickenCurry', 'chickpeas', 1.5, '1½ tins', 1),
  ('chickenCurry', 'toms', 1, '1 tin', 2),
  ('chickenCurry', 'onions', 0.25, '2 onions', 3),
  ('chickenCurry', 'rice', 0.35, '350g', 4),
  ('chickenCurry', 'pantry', 0.1, 'curry spices & oil', 5),
  ('beanChilli', 'kidneyBeans', 2, '2 tins', 0),
  ('beanChilli', 'chickpeas', 1, '1 tin', 1),
  ('beanChilli', 'toms', 2, '2 tins', 2),
  ('beanChilli', 'onions', 0.25, '2 onions', 3),
  ('beanChilli', 'rice', 0.35, '350g', 4),
  ('beanChilli', 'pantry', 0.1, 'chilli spices', 5),
  ('pancakes', 'oats', 0.12, '120g', 0),
  ('pancakes', 'eggs', 0.25, '3 eggs', 1),
  ('pancakes', 'banana', 0.25, '2 bananas', 2),
  ('pancakes', 'greekYog', 0.15, '150g', 3),
  ('shakshuka', 'eggs', 0.33, '4 eggs', 0),
  ('shakshuka', 'chickpeas', 1, '1 tin', 1),
  ('shakshuka', 'toms', 2, '2 tins', 2),
  ('shakshuka', 'onions', 0.2, '1 onion', 3),
  ('shakshuka', 'bread', 0.2, '3 slices', 4),
  ('shakshuka', 'pantry', 0.06, 'paprika & cumin', 5),
  ('peanutNoodles', 'tofu', 1, '1 block', 0),
  ('peanutNoodles', 'noodles', 0.8, '200g', 1),
  ('peanutNoodles', 'pb', 0.15, '50g', 2),
  ('peanutNoodles', 'frozenVeg', 0.4, '400g', 3),
  ('peanutNoodles', 'pantry', 0.06, 'soy & chilli flakes', 4),
  ('fajitaWraps', 'chickenBreast', 0.45, '450g', 0),
  ('fajitaWraps', 'wraps', 0.5, '4 wraps', 1),
  ('fajitaWraps', 'onions', 0.3, '2 onions', 2),
  ('fajitaWraps', 'pantry', 0.08, 'fajita spices & oil', 3)
) as v(meal_slug, ingredient_key, pack_fraction, human_quantity, sort_order)
join public.meals me on me.slug = v.meal_slug
join public.ingredients ing on ing.key = v.ingredient_key
;
