import { ThemeToggle } from "../../lib/theme/ThemeToggle";

/** Public page, reachable signed-in or signed-out — linked from the landing page and
 * paywall footers. Placeholder bracketed fields need filling in with real business
 * details before this is relied on for live billing; see the note at the top. */
export function PrivacyPage({ onBack }: { onBack: () => void }) {
  return (
    <div className="bwrap" style={{ maxWidth: 720, margin: "0 auto", padding: "24px 20px" }}>
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 18 }}>
        <button className="linklike" onClick={onBack}>
          ← Back
        </button>
        <ThemeToggle />
      </div>
      <h1 className="ppp-disp" style={{ fontSize: 26, textTransform: "uppercase", margin: "0 0 4px" }}>
        Privacy Policy
      </h1>
      <p style={{ fontSize: 12.5, color: "var(--muted)", margin: "0 0 20px" }}>Last updated: 20 July 2026</p>

      <div className="bad" style={{ fontSize: 12.5, padding: "10px 14px", marginBottom: 20 }}>
        Draft placeholder — replace the bracketed [business name/address/contact] fields
        below with your real registered details before relying on this for live billing.
        This is a solid starting draft, not a substitute for legal review.
      </div>

      <section style={{ fontSize: 14, lineHeight: 1.6 }}>
        <h2>1. Who we are</h2>
        <p>
          This policy explains how Protein/Pound, operated by [your business name / sole
          trader name] of [registered address] ("we", "us"), collects and uses your
          personal data. We're the data controller for the purposes of UK GDPR. Contact us
          at [contact email] with any questions or requests.
        </p>

        <h2>2. What we collect</h2>
        <ul>
          <li>Account data: your email address and encrypted password (handled by our authentication provider, Supabase).</li>
          <li>Profile data: daily calorie/protein targets and weekly budget, if you set them.</li>
          <li>Content you create: meal plans, saved recipes, custom-priced recipes, and any text you type into the AI recipe generator.</li>
          <li>Billing data: your subscription status and Stripe customer/subscription ID. We never see or store your card details — Stripe handles those directly.</li>
          <li>Basic technical data: standard web server logs (IP address, browser type) generated by our hosting providers.</li>
        </ul>

        <h2>3. How we use it</h2>
        <p>
          To provide the service (running your meal plans, remembering your recipes,
          generating AI recipes, running your subscription), to keep the service secure,
          and to communicate with you about your account or billing when necessary. We
          don't sell your personal data, and we don't use it for advertising.
        </p>

        <h2>4. Who we share it with</h2>
        <p>We use a small number of processors to run the service, each only for what they need to do their job:</p>
        <ul>
          <li><strong>Supabase</strong> — hosts our database and handles authentication.</li>
          <li><strong>Stripe</strong> — processes payments and manages your subscription. Card details go directly to Stripe; we never handle them.</li>
          <li><strong>Google (Gemini API)</strong> — processes the text you submit to the AI recipe generator, to generate a recipe in response.</li>
          <li><strong>Vercel</strong> — hosts the website itself.</li>
        </ul>
        <p>We don't share your data with anyone else, and we don't sell it.</p>

        <h2>5. Legal basis</h2>
        <p>
          We process your data under UK GDPR on the basis of: performing our contract
          with you (running the service and your subscription), and our legitimate
          interest in keeping the service secure and working reliably.
        </p>

        <h2>6. How long we keep it</h2>
        <p>
          We keep your account data for as long as your account is active. If you delete
          your account, we delete your personal data within a reasonable period, except
          where we're required to keep billing records for tax/accounting purposes.
        </p>

        <h2>7. Your rights</h2>
        <p>Under UK GDPR, you have the right to:</p>
        <ul>
          <li>Access the personal data we hold about you</li>
          <li>Have inaccurate data corrected</li>
          <li>Have your data deleted ("right to be forgotten")</li>
          <li>Object to or restrict certain processing</li>
          <li>Request a copy of your data in a portable format</li>
        </ul>
        <p>
          To exercise any of these, email [contact email]. You also have the right to
          complain to the UK Information Commissioner's Office (ico.org.uk) if you think
          we've mishandled your data.
        </p>

        <h2>8. Cookies</h2>
        <p>
          We use only the essential cookies/local storage needed to keep you signed in and
          remember your theme preference (light/dark). We don't use tracking or
          advertising cookies.
        </p>

        <h2>9. Changes to this policy</h2>
        <p>
          We may update this policy from time to time. We'll update the date at the top of
          this page when we do.
        </p>
      </section>
    </div>
  );
}
